spring:
 profiles: dev
 application:
  name: eureka-service-discovery
server:
 port: ${PORT:8762}
eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false
  server:
   waitTimeInMsWhenSyncEmpty: 0
