spring:
  profiles: dev
  application:
    name: receiver-head-hunter
  skillsmonster:
    schedule:
      vacancy_searcher: "0 20 1 * * *"
      queue_updater: "*/30 * * * * *"
      vacancy_loader: "*/10 * * * * *"
    host: "https://api.hh.ru/"
    api:
      version: v1
  rabbitmq:
    host: dev.api.revolveronline.ru
    username: worker
    password: worker
    port: 8082
    virtual-host: "loc"
    concurrentConsumers: 2
    maxConcurrentConsumers: 4
    dataloader:
      queue:
        level1: data-loader-spark-level-1.queue
        level2: data-loader-spark-level-2.queue
        level3: data-loader-spark-level-3.queue
        level4: data-loader-spark-level-4.queue
        shareHolder: data-loader-spark.shareholder.queue
        relatedParty: data-loader-spark.relatedparty.queue
      exchange: data-loader-spark.exchange
      routingKey: spark.loader.messages.key
      shareHolderRoutingKey: spark.loader.shareholder.routing.key
      relatedPartyRoutingKey: spark.loader.relatedparty.routing.key
      companyLoadedRoutingKey: spark.loader.companyloaded.routing.key
      resultsRoutingKey: spark.loader.results.key
      deadLetterQueue: data-loader-spark.dead-letter.queue
      deadLetterExchange: data-loader-spark.dead-letter.exchange   
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://rumos0154:5432/skillsmonster"
    username: postgres
    password: postgres
# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: com.masdmtr.skillsmonster.json.CustomPostgreSqlDialect
    generate-ddl: true
    hibernate:
      dialect: com.masdmtr.skillsmonster.json.CustomPostgreSqlDialect
      ddl-auto: validate
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#     enable_lazy_load_no_trans: true
      connection:
        charSet: UTF-8
#     format-sql: true
    use-sql-comments: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.51:8761/eureka}
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 5
server:
  port: 0
debug: false
logging:
  level:
    org.springframework.web: INFO
    guru.springframework:
      controllers: DEBUG
      org.hibernate: ERROR
  file: logs/spring-boot-logging.log
management:
 security:
  enabled: false
